# A study of video QoE in Africa

## Characterization of probes

In [39]:
import json
import pandas as pd

df = pd.read_json('data/probes-29042019.json', orient='colums')

df = pd.DataFrame(df['GetProbesResult']['Probes'])

ccs = ['EG', 'BJ', 'CI', 'CV', 'GH', 'GM', 'GN', 'GW', 'AO', 'CF', 'CG', 'CM', 'GA', 'GQ', 'TD', 'BI', 'DJ', 'ER', 'ET', 'KM', 'BW', 'MA', 'SD', 'TN', 'LR', 'ML', 'MR', 'NE', 'NG', 'SL', 'SN', 'TG', 'ST', 'KE', 'MG', 'MU', 'MW', 'MZ', 'RE', 'RW', 'SC', 'SO', 'UG', 'LS', 'NA', 'SZ', 'ZA', 'DZ', 'EH', 'LY', 'BF', 'SH', 'CD', 'TZ', 'YT', 'ZM', 'ZW']

df = df.loc[df['CountryCode'].isin(ccs)]

In [40]:
df.head()

,ASN,CityName,ConnectionType,CountryCode,DNSResolver,GeolocationAccuracy,IPAddress,Latitude,Longitude,Network,NetworkID,Platform,ProbeID,Screensize,Version
3,36937.0,Pretoria,"Wireless80211,Ethernet",ZA,165.73.227.253,5000,165.73.226.174,-25.76,28.14,WAN 4 U cc,105679.0,PC,b7f37d52-c167-4469-becb-725be1034fa5,1366x768,1.0.44.0
5,37457.0,Pretoria,Ethernet,ZA,196.43.42.232,5000,105.227.152.134,-25.76,28.14,Telkom Internet,422.0,PC,cea2de8f-4491-4e6a-84e9-578618b6a303,1280x1024,1.0.44.0
6,8452.0,Cairo,Wireless80211,EG,,10000,41.235.64.134,30.08,31.29,TE Data,121350.0,PC,806bd2cc-0373-43cc-943c-86322d162f74,1366x768,1.0.44.0
14,30986.0,Unknown,Wireless80211,GH,196.201.61.141,25000,154.160.9.71,5.55,-0.22,MTN Ghana,92811.0,PC,52569b75-a1fb-4806-bfcf-9d1e639b25fc,1366x768,1.0.44.0
15,37457.0,Pretoria,Ethernet,ZA,196.43.45.229,25000,102.250.2.138,-25.76,28.14,Telkom Internet,422.0,PC,a209efd4-7d25-4da5-b0ae-c206188c91ff,1280x1024,1.0.44.0

In [41]:
df_count = df.groupby(['CountryCode']).size().to_frame(name = 'count').reset_index()
df_count = df_count.sort_values(by='count', ascending=False)

#

In [42]:
df_count

   CountryCode  count
11          MA    132
21          ZA     54
19          TN     54
5           EG     48
4           DZ     34
8           KE      7
14          NG      4
16          SN      3
22          ZW      3
7           GH      3
3           DJ      3
15          RE      2
6           GA      2
18          TD      2
20          UG      2
0           AO      2
9           LR      1
10          LS      1
1           BI      1
12          MU      1
13          NA      1
17          SO      1
2           CM      1

In [55]:
import plotly.plotly as py
import pandas as pd

limits = [(0,10),(11,50),(51,100),(101,200),(201,500)]
colors = ["rgb(0,116,217)","rgb(255,65,54)","rgb(133,20,75)","rgb(255,133,27)","lightgrey"]
cities = []
scale = 500

for i in range(len(limits)):
    lim = limits[i]
    df_sub = df[lim[0]:lim[1]]
    
    city = dict(
        type = 'scattergeo',
        locationmode = 'country names',
        lon = df_sub['Longitude'],
        lat = df_sub['Latitude'],
        marker = dict(
            size = df_count['count']*5,
            color = colors[i],
            line = dict(width=0.5, color='rgb(40,40,40)'),
            sizemode = 'area'
        ),
        name = '{0} - {1}'.format(lim[0],lim[1]) )
    cities.append(city)

layout = dict(
        title = 'Probes distribution April 2019',
        showlegend = True,
        geo = dict(
            scope='africa',
            projection=dict( type='country names' ),
            showland = True,
            landcolor = 'rgb(217, 217, 217)',
            subunitwidth=1,
            countrywidth=1,
            subunitcolor="rgb(255, 255, 255)",
            countrycolor="rgb(255, 255, 255)"
        ),
    )

fig = dict( data=cities, layout=layout )
py.iplot( fig, validate=False, filename='d3-bubble-map-populations' )

In [58]:
import plotly.plotly as py
import pandas as pd

limits = [(0,10),(11,50),(51,100),(101,200),(201,500)]
colors = ["rgb(0,116,217)","rgb(255,65,54)","rgb(133,20,75)","rgb(255,133,27)","lightgrey"]
cities = []
scale = 500

for i in range(len(limits)):
    lim = limits[i]
    df_sub = df[lim[0]:lim[1]]
    
    city = dict(
        type = 'scattergeo',
        locationmode = 'country names',
        lon = df_sub['Longitude'],
        lat = df_sub['Latitude'],
        mode = "markers",
        name = '{0} - {1}'.format(lim[0],lim[1]) )
    cities.append(city)

layout = dict(
        title = 'Probes distribution April 2019',
        showlegend = True,
        geo = dict(
            scope='africa',
            projection=dict( type='country names' ),
            showland = True,
            landcolor = 'rgb(217, 217, 217)',
            subunitwidth=1,
            countrywidth=1,
            subunitcolor="rgb(255, 255, 255)",
            countrycolor="rgb(255, 255, 255)"
        ),
    )

fig = dict( data=cities, layout=layout )
py.iplot( fig, validate=False, filename='d3-bubble-map-populations' )